### ISSUE TITLE
Error: Only ext-link-type="uri" is supported

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#8]
Earlier I tried validating some of the early XML files, and very few were passing validation of my drafted validating procedure. I converted the files again and tried validating, and they were still not passing.

Validating one of these files (`elife-00093-v1.xml`) and observing the test output, the Texture persistence tests return this,

```
not ok 1 Uncaught error: Error: Error: Only ext-link-type="uri" is supported
```

I think these are probably related to the component DOI values, like for example `<ext-link ext-link-type="doi" xlink:href="10.7554/eLife.00093.001">http://dx.doi.org/10.7554/eLife.00093.001</ext-link>`.

@FAtherden-eLife do you have some ideas please about whether and how these tags could be removed in your XQuery?

I got a blank white screen in Texture when viewing the `elife-00093-v1.xml` file. After I removed all the `<ext-link ext-link-type="doi"...>` tags then it appeared in Texture!

**Comment by gnott** [comment]
I noticed something small on `elife-00093-v1.xml` after conversion too - the space character before the `<italic>` tag in the `<article-title>` is missing from the XQuery output file.

The original XML has

```
<article-title>Population structuring of multi-copy, antigen-encoding genes in <italic>Plasmodium falciparum</italic></article-title>
```

The output of the XQuery is

```
<article-title>Population structuring of multi-copy, antigen-encoding genes in<italic>Plasmodium falciparum</italic>
```

I noticed the lack of spacing in the Texture window when viewing the article, causing me to look at the XML.

**Comment by fred-atherden** [comment]
Thanks @gnott - that's interesting - I didn't know that old markup was used in place of `object-id`. Should be resolved in my latest commit.

With regard to the spacing error - I think this is to do with the local BaseX configuration. I think chop whitespace is set to true by default. If you use the 'get CHOP' command (most easily done by simply typing it into the command bar and hitting enter), is the result true or false? If it's true, then this will certainly be the cause.

(If my hunch is correct), then this can be resolved [by setting this option](http://docs.basex.org/wiki/Options) so that it's always false in the [configuration file(s)](http://docs.basex.org/wiki/Configuration#Configuration_Files), or simply set it each time it's opened with the command 'set CHOP false'.

Let me know!

**Comment by gnott** [comment]
I think the `<ext-link>` error is solved by this, thanks @FAtherden-eLife. 

I'll consider the `CHOP` option too. Since yesterday I started testing using Zorba instead of BaseX, and as of this morning I got that working. Zorba is about five times faster than BaseX, which really helps when converting thousands of files. The whitespace is not altered right now but I have a basic example I will continue trying to see if it is something I might recommend for this project.

**Comment by gnott** [comment]
There is still an error with some of these early files, the reason is undetermined so far, the message being `Error: JATS import failed`. I'll open a new ticket for figuring out why.

**Comment by gnott** [comment]
Closed too early, sorry.

In `elife-00067-v1.xml` there is another `<ext-link>` tag of `ext-link-type="doi"` in the body:

```
<supplementary-material id="SD1-data">
<object-id pub-id-type="doi">10.7554/eLife.00067.017</object-id>
<label>Supplementary file 1.</label>
<caption>
<p>DNA sequences used in measurements</p>
<p>
<bold>DOI:</bold>
<ext-link ext-link-type="doi" xlink:href="10.7554/eLife.00067.017">http://dx.doi.org/10.7554/eLife.00067.017</ext-link>
</p>
</caption>
<media mime-subtype="pdf" mimetype="application" xlink:href="elife-00067-supp1-v1.pdf"/>
</supplementary-material>
```

This one is causing validation problems (as well as something else in this particular article I am narrowing in on).

**Comment by fred-atherden** [comment]
Ah it's because at each copy/modify stage elements (and their descendants) are copied as they appear at that moment.

So the [current query](https://github.com/elifesciences/elife-jats-2-dar-jats/blob/d693eaa9e175b86a3ecc34b7270d210bc1f68af2/xquery/elife2dar.xq#L136-L141) doesn't account for any `ext-link`s which might be in a `sec[@sec-type="additional-information"]` or `sec[@sec-type="supplementary-material"]` since it's in the same copy/modify stage as [this](https://github.com/elifesciences/elife-jats-2-dar-jats/blob/d693eaa9e175b86a3ecc34b7270d210bc1f68af2/xquery/elife2dar.xq#L104-L107).

I think it's best to start a new stage, since this could be affected by many of the other steps in other stages.

**Comment by gnott** [comment]
I cannot say I understand the copies and stages in the XQuery, so please do as you wish in response to my naive PRs.
